name: Compile Code

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Set up environment
      # Add steps to set up your environment, e.g., installing dependencies

    - name: Compile Code
      run: echo "Hello world!!! hahaha"
      # Replace 'make' with the command you use to compile your code
